spring.application.name=api

# Configuração de Banco de Dados (Prioriza variáveis de ambiente do PostgreSQL, senão usa H2)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:oscardb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# JPA/Hibernate
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Console H2 (Apenas para desenvolvimento local fora do Docker)
spring.h2.console.enabled=true
