spring.application.name=api

# Configuração para H2 (Banco de dados em memória para teste fácil)
spring.datasource.url=jdbc:h2:mem:oscardb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
